# Generated by Django 3.1.7 on 2021-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='name', max_length=255, verbose_name='Imię'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='surname', max_length=255, verbose_name='Nazwisko'),
            preserve_default=False,
        ),
    ]
