# Generated by Django 3.1.7 on 2021-04-06 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (1, "Fundacja"),
                            (2, "Organizacja pozarządowa"),
                            (3, "Lokalna zbiórka"),
                        ],
                        default=1,
                        max_length=2,
                    ),
                ),
                ("categories", models.ManyToManyField(to="donation.Category")),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "address",
                    models.CharField(
                        help_text="street and house number", max_length=128
                    ),
                ),
                ("phone_number", models.CharField(max_length=9)),
                ("city", models.CharField(max_length=32)),
                ("zip_code", models.CharField(help_text="00-000", max_length=6)),
                ("pick_up_date", models.DateField()),
                ("pick_up_time", models.TimeField()),
                ("pick_up_comment", models.TextField()),
                ("categories", models.ManyToManyField(to="donation.Category")),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donation.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
